CREATE DATABASE IF NOT EXISTS baza CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE baza;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  completed TINYINT(1) DEFAULT 0,
  date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
